import Head from 'next/head'
import Video from '../components/Video'
import axios from 'axios'
import { useEffect, useState } from 'react'

export default function Home() {
  const [videoData, setVideoData] = useState([{
    channel: "Mohammad Sahil",
    description: "This is a nice song by Mohd Rafi",
    likes: 897,
    messages: 322,
    shares: 100,
    song: "Tere sang yara",
    url: "/sample.mp4",
    __v: 0,
    _id: "62c14e0db36e81791219e747"
  }])

  // const getData = async () => {
  //   const sldfj = await axios(`http://localhost:8000/v4/data`)
  //     .then(res => {
  //       const vData = res.data;
  //       setVideoData(vData);
  //       console.log(res)
  //     })
  //     .catch((e) => console.log(e))
  // }

  // useEffect(() => {
  //   getData()
  // },[])
  useEffect(() => {
    async function getData(){
      const res = await axios.get( 
        `https://tiktok-nodejs.herokuapp.com/v2/data`
        );
      setVideoData(res.data);
      console.log(res.data);
      console.log(videoData)
    };
    getData()
  },[]);
  return (
    <div className="app">
    <div className="app__videos">
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {videoData?.map((data) => {
        return (
          <Video
            key={data._id}
            url = {data.url}
            channel = {data.channel}
            description = {data.description}
            song = {data.song}
            likes = {data.likes}
            messages = {data.messages}
            shares = {data.shares}
        />
        )
      })}
      </div>
    </div>
  )
}
