import Head from 'next/head'
import Video from '../components/Video'
import axios from 'axios'
import { useEffect, useState } from 'react'

export default function Home() {
  const [videoData, setVideoData] = useState(null)

  // const getData = async () => {
  //   const sldfj = await axios(`http://localhost:8000/v4/data`)
  //     .then(res => {
  //       const vData = res.data;
  //       setVideoData(vData);
  //       console.log(res)
  //     })
  //     .catch((e) => console.log(e))
  // }

  // useEffect(() => {
  //   getData()
  // },[])
  useEffect(() => {
    async function getData(){
      const res = await axios.get( 
        `http://10.0.2.2:8000/v4/data`
        );
      setVideoData(res.data);
      console.log(res.data);
    };
    getData()
  },[]);
  return (
    <div className="app">
    <div className="app__videos">
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Video
        url = "/sample.mp4"
        channel = "Mohammad Sahil"
        description = "This is a nice song by Mohd Rafi"
        song = "Tere sang yara"
        likes = {897}
        messages = {322}
        shares = {100}
      />
      <Video
        url = "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"
        channel = "Mohammad Sahil"
        description = "This is a nice song by Mohd Rafi"
        song = "Tere sang yara"
        likes = {897}
        messages = {322}
        shares = {100}
      />
      </div>
    </div>
  )
}
