import Head from 'next/head'
import Video from '../components/Video'

export default function Home() {
  return (
    <div className="app">
    <div className="app__videos">
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Video
        url = "/sample.mp4"
        channel = "Mohammad Sahil"
        description = "This is a nice song by Mohd Rafi"
        song = "Tere sang yara"
        likes = {897}
        messages = {322}
        shares = {100}
      />
      <Video
        url = "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"
        channel = "Mohammad Sahil"
        description = "This is a nice song by Mohd Rafi"
        song = "Tere sang yara"
        likes = {897}
        messages = {322}
        shares = {100}
      />
      </div>
    </div>
  )
}
